Use splunkdev standard Windows runners
Simplify trigger

Use different approach for trigger

Fix .win-runners-test

Add msi-custom-actions-assemblies

Skip choco-release

Try image for agent-bundle-windows

Use servercore:ltsc2022

Use a MS image with Python

pip install pip-system-certs

Add a pip install

Use mcr.microsoft.com/windows/servercore:ltsc2022 directly

Add DigiCert to the Windows image

Change cert file

Install system certs for Python

Remove certificate import

Install choco and WiX for msi-custom-actions-package

Add remaining image entries and tentative installs

Remove choco-release since it needs github-release

Answer any "choco install" prompts with "yes"

Move choco and WiX install to shared scripts

Add sign-msi to the win runners test

Test docker on Windows runners

Fix image for test job

Fix typo on docker image command

Downgrade choco for Windows 2019

Small refactor for docker cli setup

Refactor docker cli setup

Remove image deletion from docker jobs

Remove test scaffolding

[chore] OTL-3922 Enable usetesting for linters and resolve the issues (#7014)

* [chore] OTL-3922 Enable usetesting for linters and resolve the issues

Remove leftover comment

Pin pip-system-certs and require hash check

Refactor choco and docker cli

No downloads for choco install

Add all necessary nupkg files

Change Set-ExecutionPolicy scope

Pin git and check respective hash

Re-factor scripts and nupkg download

Undo typo

Disable feature gate processor.resourcedetection.propagateerrors (#7030)

Signed-off-by: Dani Louca <dlouca@splunk.com>

Update OpenTelemetry Dependencies to latest (#7028)

* Update OpenTelemetry Dependencies to latest

* [chore] fix lint

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] fix lint"

This reverts commit 5bf59d814e703cf6f651719fe040a9cc903b6108.

* [chore] Fix lint issue where CI was failing with this error:
Error: tests/testutils/endpoint.go:84:25: directive `//nolint:gosec` is unused for linter "gosec" (nolintlint)
	return uint16(portInt) //nolint:gosec
The error goes away after upgrading golangci-lint from v2.5.0 to v2.7.2 , which also updates gosec, however it introduces issues with strconcat lint that I addresed in the same commit

Signed-off-by: Dani Louca <dlouca@splunk.com>

* [chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:
2025/12/18 05:03:15 main.go:92: application run finished with error: cannot start pipelines: failed to start "resourcedetection" processor: unable to fetch task metadata: Get "http://localhost/task": dial tcp [::1]:80: connect: connection refused
The issue is introduced by a change in resource detection https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/3fe99b89ac2c398844416f3b7e11b2dfd5071bbd which promoted the feature gate "allowErrorPropagationFeatureGate"  to stable and that automatically enabled it.
This feature will cause the collector to exits when it received the error from ecs detector.
Removing the env variable "ECS_CONTAINER_METADATA_URI_V4=http://localhost" will cause the detector to return nil provider, ie: noop , this behavior has changed after we added "ECS_CONTAINER_METADATA_URI_V4=http://localhost" to workaround the error returned by the detector

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:"

This reverts commit d2cba5fa89a316401bd8610192699ffe2525f6f2.

* debug failures

Signed-off-by: Dani Louca <dlouca@splunk.com>

* debug failures-2

Signed-off-by: Dani Louca <dlouca@splunk.com>

* update test expected values

Signed-off-by: Dani Louca <dlouca@splunk.com>

---------

Signed-off-by: Dani Louca <dlouca@splunk.com>
Co-authored-by: Dani Louca <59848726+dloucasfx@users.noreply.github.com>
Co-authored-by: Dani Louca <dlouca@splunk.com>

[chore] prepare Changelog v0.142.0 (#7033)

* [chore] prepare Changelog v0.142.0

Signed-off-by: Dani Louca <dlouca@splunk.com>

* review updates 1

Signed-off-by: Dani Louca <dlouca@splunk.com>

---------

Signed-off-by: Dani Louca <dlouca@splunk.com>

Review suggestions

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

Add DigiCert to the Windows image

Change cert file

Remove certificate import

Remove choco-release since it needs github-release

Add sign-msi to the win runners test

Test docker on Windows runners

Fix image for test job

Fix typo on docker image command

Downgrade choco for Windows 2019

Small refactor for docker cli setup

Refactor docker cli setup

Remove image deletion from docker jobs

Remove test scaffolding

[chore] OTL-3922 Enable usetesting for linters and resolve the issues (#7014)

* [chore] OTL-3922 Enable usetesting for linters and resolve the issues

Remove leftover comment

Pin pip-system-certs and require hash check

No downloads for choco install

Add all necessary nupkg files

Re-factor scripts and nupkg download

Undo typo

Disable feature gate processor.resourcedetection.propagateerrors (#7030)

Signed-off-by: Dani Louca <dlouca@splunk.com>

Update OpenTelemetry Dependencies to latest (#7028)

* Update OpenTelemetry Dependencies to latest

* [chore] fix lint

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] fix lint"

This reverts commit 5bf59d814e703cf6f651719fe040a9cc903b6108.

* [chore] Fix lint issue where CI was failing with this error:
Error: tests/testutils/endpoint.go:84:25: directive `//nolint:gosec` is unused for linter "gosec" (nolintlint)
	return uint16(portInt) //nolint:gosec
The error goes away after upgrading golangci-lint from v2.5.0 to v2.7.2 , which also updates gosec, however it introduces issues with strconcat lint that I addresed in the same commit

Signed-off-by: Dani Louca <dlouca@splunk.com>

* [chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:
2025/12/18 05:03:15 main.go:92: application run finished with error: cannot start pipelines: failed to start "resourcedetection" processor: unable to fetch task metadata: Get "http://localhost/task": dial tcp [::1]:80: connect: connection refused
The issue is introduced by a change in resource detection https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/3fe99b89ac2c398844416f3b7e11b2dfd5071bbd which promoted the feature gate "allowErrorPropagationFeatureGate"  to stable and that automatically enabled it.
This feature will cause the collector to exits when it received the error from ecs detector.
Removing the env variable "ECS_CONTAINER_METADATA_URI_V4=http://localhost" will cause the detector to return nil provider, ie: noop , this behavior has changed after we added "ECS_CONTAINER_METADATA_URI_V4=http://localhost" to workaround the error returned by the detector

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:"

This reverts commit d2cba5fa89a316401bd8610192699ffe2525f6f2.

* debug failures

Signed-off-by: Dani Louca <dlouca@splunk.com>

* debug failures-2

Signed-off-by: Dani Louca <dlouca@splunk.com>

* update test expected values

Signed-off-by: Dani Louca <dlouca@splunk.com>

---------

Signed-off-by: Dani Louca <dlouca@splunk.com>
Co-authored-by: Dani Louca <59848726+dloucasfx@users.noreply.github.com>
Co-authored-by: Dani Louca <dlouca@splunk.com>

[chore] prepare Changelog v0.142.0 (#7033)

* [chore] prepare Changelog v0.142.0

Signed-off-by: Dani Louca <dlouca@splunk.com>

* review updates 1

Signed-off-by: Dani Louca <dlouca@splunk.com>

---------

Signed-off-by: Dani Louca <dlouca@splunk.com>

Review suggestions

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>