Update OpenTelemetry Dependencies to latest (#7028)
* Update OpenTelemetry Dependencies to latest

* [chore] fix lint

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] fix lint"

This reverts commit 5bf59d814e703cf6f651719fe040a9cc903b6108.

* [chore] Fix lint issue where CI was failing with this error:
Error: tests/testutils/endpoint.go:84:25: directive `//nolint:gosec` is unused for linter "gosec" (nolintlint)
	return uint16(portInt) //nolint:gosec
The error goes away after upgrading golangci-lint from v2.5.0 to v2.7.2 , which also updates gosec, however it introduces issues with strconcat lint that I addresed in the same commit

Signed-off-by: Dani Louca <dlouca@splunk.com>

* [chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:
2025/12/18 05:03:15 main.go:92: application run finished with error: cannot start pipelines: failed to start "resourcedetection" processor: unable to fetch task metadata: Get "http://localhost/task": dial tcp [::1]:80: connect: connection refused
The issue is introduced by a change in resource detection https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/3fe99b89ac2c398844416f3b7e11b2dfd5071bbd which promoted the feature gate "allowErrorPropagationFeatureGate"  to stable and that automatically enabled it.
This feature will cause the collector to exits when it received the error from ecs detector.
Removing the env variable "ECS_CONTAINER_METADATA_URI_V4=http://localhost" will cause the detector to return nil provider, ie: noop , this behavior has changed after we added "ECS_CONTAINER_METADATA_URI_V4=http://localhost" to workaround the error returned by the detector

Signed-off-by: Dani Louca <dlouca@splunk.com>

* Revert "[chore] Fix broken test caused by a break fix feature gate promotion that is causing this error:"

This reverts commit d2cba5fa89a316401bd8610192699ffe2525f6f2.

* debug failures

Signed-off-by: Dani Louca <dlouca@splunk.com>

* debug failures-2

Signed-off-by: Dani Louca <dlouca@splunk.com>

* update test expected values

Signed-off-by: Dani Louca <dlouca@splunk.com>

---------

Signed-off-by: Dani Louca <dlouca@splunk.com>
Co-authored-by: Dani Louca <59848726+dloucasfx@users.noreply.github.com>
Co-authored-by: Dani Louca <dlouca@splunk.com>